#!/usr/bin/env python

"""Packages the rsyslog client"""

__author__ = 'edelman@room77.com (Nicholas Edelman)'
__copyright__ = 'Copyright 2013 Room77, Inc.'

import argparse
import os
import shutil
import subprocess
import yaml

class RsyslogClientPackager(object):
  FILES = [ '50-default.conf', 'rsyslog.conf' ]

  def __init__(self, args):
    self._my_dir = os.path.dirname(__file__)
    self._out_dir = args.package_dir

  def packager(self):
    for f in self.FILES:
      shutil.copyfile(os.path.join(self._my_dir, f),
                      os.path.join(self._out_dir, f))

if __name__ == '__main__':
  parser = argparse.ArgumentParser()
  parser.add_argument('package_dir',
                      help='the directory to write the package files')
  args = parser.parse_args()

  rsp = RsyslogClientPackager(args)
  rsp.packager()

